TheDrive/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from driver import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include(('user.urls', 'user'), namespace='user')),
    path('',views.index,name="index"),
    path('drive/',include(('driver.urls', 'driver'), namespace='driver')),
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views
#from .views import RegisterView
app_name = "user"


urlpatterns = [
    path('login/',views.loginUser,name = "login"),
    path('register/',views.register,name = "register"),
    path('logout/',views.logoutUser,name = "logout"),

]

driver/models.py
from django.db import models

# Create your models here.


class Organization(models.Model):
    name = models.CharField(verbose_name='Organization',max_length=150, unique=True)

    def __str__(self):
        return self.name

class OrganizationMember(models.Model):
    organization_member = models.ForeignKey(Organization, on_delete=models.CASCADE)
    user = models.ForeignKey('user.User', blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return "Organization : %s - User : %s" %(self.organization_member,self.user)

class Folder(models.Model):
    folder_name = models.CharField(verbose_name='Folder Name', max_length=170)
    organization_folder = models.ForeignKey(Organization, on_delete=models.CASCADE)

    def __str__(self):
        return self.folder_name

class DocumentPackage(models.Model):
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    created_by = models.ForeignKey(OrganizationMember, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    folder = models.ForeignKey(Folder, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return "Organization : %s - Folder : %s" %(self.organization, self.folder)

class Document(models.Model):
    package = models.ForeignKey(DocumentPackage, on_delete=models.CASCADE)
    file = models.FileField(blank=False,verbose_name='File')

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>The Drive</title>
</head>
<body>

    <div class="container" style="margin-top:15px;text-align:center;width:100%;">
        {% include 'messages.html' %}
    </div>

    {% block icerik %}

    {% endblock icerik %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

templates/login.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block icerik %}
<body style = background-color:midnightblue;color:White;>
<div class="container">
    <h3>Giriş Yap</h3>
    <hr style="background:White;">
  <div class="row">
    <div class="col">
      <form method = "post">
        {% csrf_token %}
        {{form|crispy}}
        <br>
        <button type = "submit" class = "btn btn-primary">Giriş Yap</button>
    </div>
    
    </form>
  </div>
  <br>
  <div class="col"> 
        Eğer bir hesabın yoksa, <a href="/user/register">Kayıt Ol</a>
    </div>
</div>
</body>
<style>
 #id_username, #id_password{
   border-radius:10px;
   padding: 3px 5px;
   margin: 2px;
 }
</style>

{% endblock %}

templates/mail_send.html
{% extends "index.html"%}

{% block icerik %}
    <div class="container-fluid">
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            <div class="row">
                <div id="border_div">
                    <label class="mail_label">Subject : </label>
                    <input class="input_field" type="text" placeholder="Title" value="" name="subject" id="id_subject"/> <br>
                    <label class="mail_label">To : </label>
                    <input class="input_field" type="text" placeholder="Email Adress" value="" name="to" id="id_to" /> <br>

                    <label class="mail_label" id="label_object">Object : </label> <br>
                    <textarea class="input_field" name = "object" id="id_object"></textarea> <br>
                    {% for form in document_form %}
                        <label class="mail_label">{{ form.label }} :</label>
                        {{ form }} <br>
                    {% endfor %}
                    <!-- <label class="mail_label">File : </label>
                    <input class="input_field" type="file" name="file" id="id_file" multiple/> <br> -->

                    <input type="submit" class="input_button" value="Submit" />
                </div>
            </div>
        </form>
    </div>
<style>
    #border_div{
        border: 2px solid rgba(10,20,30,0.7);
        margin-left : 100px;
        padding : 20px;
        -webkit-box-shadow: 10px 10px 10px 5px rgba(10,20,30,0.75);
        -moz-box-shadow: 10px 10px 10px 5px rgba(10,20,30,0.75);
        box-shadow: 0px 0px 15px 12px rgba(10,20,30,0.75);
    }
    #label_object{
        margin-top: -100px;
    }
    .mail_label{
        margin-right: 20px;
        width: 100px;
    }
    #id_object{
        height: 500px;
        margin-left: 124px;
        margin-top: -30px;
    }
    .input_field{
        margin-top: 5px;
        width: 500px;
        border: 2px outset rgba(164,207,245,0.75);
        border-radius: 5px;
        padding: 5px;
        transition: 0.25s
    }
    .input_field:hover, .input_field:focus, .input_button:hover{
        -webkit-box-shadow: 0px 0px 10px 5px rgba(164,207,245,0.75);
        -moz-box-shadow: 0px 0px 10px 5px rgba(164,207,245,0.75);
        box-shadow: 0px 0px 10px 5px rgba(164,207,245,0.75);
    }
    .input_button{
        width: 100px;
        margin-left: 124px;
        margin-top: 20px;
        border: 2px outset rgba(164,207,245,0.75);
        border-radius: 5px;
        padding: 5px;
        transition: 0.25s
    }
    #id_package{
        margin-bottom: 10px;
    }
</style>
{% endblock %}

templates/main_page.html
{% extends "index.html"%}

{% block icerik %}

<div class="container">
    <div class="row">
        <div class="col-md-12 card-div">
            <div class="card">
               <div class="card-header d-flex justify-content-between" id="pointer" onclick="onClickEvent('vis','aciklama')">
                    <h4 class="d-inline">Organization <small style="font-size:12px;" id="aciklama">(Click for show)</small></h4>
               </div>
               <div class="card-body" id="vis" style="display:none">
                   <form method="POST">
                    {% csrf_token %}
                    {% for form in organization_form %}
                       <label class="form_label">{{ form.label }} :</label>
                       {{form}} <br>
                       {% endfor %}
                    <button type="submit" class="btn btn-outline-primary">Ok</button>
                </form>
              </div>
            </div>

            <!--<div class="card">
               <div class="card-header d-flex justify-content-between" id="pointer2" onclick="onClickEvent('vis2','aciklama2')">
                    <h4 class="d-inline">Document Form <small style="font-size:12px;" id="aciklama2">(Click for show)</small></h4>
               </div>
               <div class="card-body" id="vis2" style="display:none">
                   <form method="POST">
                        {% csrf_token %}
                        {% for form in document_form %}
                            <label class="form_label">{{ form.label }} :</label>
                            {{ form }} <br>
                        {% endfor %}
                        <button type="submit" class="btn btn-outline-primary">Ok</button>
                    </form>
              </div>
            </div> -->

            <div class="card">
               <div class="card-header d-flex justify-content-between" id="pointer3" onclick="onClickEvent('vis3','aciklama3')">
                    <h4 class="d-inline">Document Package Form <small style="font-size:12px;" id="aciklama3">(Click for show)</small></h4>
               </div>
               <div class="card-body" id="vis3" style="display:none">
                   <form method="POST">
                        {% csrf_token %}
                        {% for form in document_package_form %}
                            <label class="form_label">{{ form.label }} :</label>
                            {{ form }} <br>
                        {% endfor %}
                       <button type="submit" class="btn btn-outline-primary">Ok</button> <br>
                   </form>
              </div>
            </div>

             <div class="card">
               <div class="card-header d-flex justify-content-between" id="pointer4" onclick="onClickEvent('vis4','aciklama4')">
                    <h4 class="d-inline">Organization Member Form <small style="font-size:12px;" id="aciklama4">(Click for show)</small></h4>
               </div>
               <div class="card-body" id="vis4" style="display:none">
                    <form method="POST">
                        {% csrf_token %}
                        {% for form in organization_member_form %}
                            <label class="form_label">{{ form.label }} :</label>
                            {{ form }} <br>
                        {% endfor %}
                        <button type="submit" class="btn btn-outline-primary">Ok</button> <br>
                    </form>
              </div>
            </div>

             <div class="card">
               <div class="card-header d-flex justify-content-between" id="pointer5" onclick="onClickEvent('vis5','aciklama5')">
                    <h4 class="d-inline">Folder Form <small style="font-size:12px;" id="aciklama5">(Click for show)</small></h4>
               </div>
               <div class="card-body" id="vis5" style="display:none">
                    <form method="POST">
                        {% csrf_token %}
                        {% for form in folder_form %}
                            <label class="form_label">{{ form.label }} :</label>
                            {{ form }} <br>
                        {% endfor %}
                        <button type="submit" class="btn btn-outline-primary">Ok</button> <br>
                    </form>
              </div>
            </div>

        </div>
    </div>
</div>
<style>
    .card{
        margin-top: 5px;
        margin-bottom: 5px;
    }
    #pointer, #pointer2, #pointer3, #pointer4, #pointer5{
        cursor:pointer;
    }
    .form_label{
        margin-right: 20px;
        width: 100px;
     }
</style>
<script>
function onClickEvent(divide, yaziDegis)
{

    var opacity = 0
    var divide_var = document.getElementById(divide)
    var yaziDegis_var = document.getElementById(yaziDegis)
    if (divide_var.style.display == "block")
    {
        yaziDegis_var.innerHTML = '(Click for show)'
        divide_var.style.display = 'none'
    }
    else
    {
        const animation = setInterval(() => {
            if (opacity >= 1)
            {
                clearInterval(animation)
            }
            else
            {
                if (divide_var.style.display !== 'block'){
                    yaziDegis_var.innerHTML = '(Click for hide)'
                    divide_var.style.display = 'block'
                }
                opacity = opacity + 0.05
                divide_var.style.opacity = opacity
                console.log(opacity)
            }
        }, 25)
    }
}
</script>

{% endblock icerik %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{message.tags}} alert-dismissible" id="alert" role="alert">
            <button type="button"  class="close" id="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

<script>
var alertBox = document.getElementById("alert");

document.getElementById("close").onclick = function (e){
    alertBox.style.display = "none";
}
</script>

templates/register.html
{% extends "index.html"%}
{% load crispy_forms_tags %}

{% block icerik %}


<div class="row" style="margin-top:10px;">
  <div class="col-md-6 offset-md-3">
        <h3>Register</h3>
    <hr style="background:white;">
     <form method="post" id="new_user_form">
        {% csrf_token %}
        {{form|crispy}}
        <br>
        <button type="submit" class ="btn btn-danger">Register</button>
    </form>
  </div>
</div>

{% endblock icerik %}